server:
  port: 8080

spring:
  application:
    name: HealthHyper
  datasource:
    url: jdbc:mysql://localhost:3306/health_hyper?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

app:
  jwt:
    secret: HealthHyperJwtSecretKey2026ForDemoProjectX
    expiration-hours: 72
  ai:
    base-url: https://52d030ce23074c63a2c3589460f6dac9--8000.ap-shanghai2.cloudstudio.club
    mock-enabled: false  # true=本地mock，false=调真实云AI
    api-key: HealthHyperAiToolKey2026  # AI端调用中台接口的API Key
